name: synthesizar-rtd
channels:
- defaults
- conda-forge
dependencies:
- python=3.6
- astropy
- dask
- h5py
- matplotlib
- numpy
- numba
- scipy
- sunpy>=0.8
- yt
- pip:
  - plasmapy
  - git+git://github.com/wtbarnes/fiasco.git
  
