name: synthesizar-rtd
channels:
- defaults
- conda-forge
dependencies:
- python=3.6
- astropy
- dask
- distributed
- h5py
- matplotlib
- numpy
- numba
- scipy
- sunpy
- yt
- pip:
  - sphinx-astropy
  - plasmapy
  - git+git://github.com/wtbarnes/fiasco.git
  
