# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds. A full list of packages
# that can be included can be found here:
#
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:

        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - PYTHON_VERSION=3.6
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - MAIN_CMD='python setup.py'
        - PIP_DEPENDENCIES='git+git://github.com/PlasmaPy/PlasmaPy.git git+git://github.com/wtbarnes/solarbextrapolation.git git+git://github.com/wtbarnes/fiasco.git'
        - CONDA_DEPENDENCIES='dask h5py matplotlib scipy sunpy yt'
        - CONDA_CHANNELS='conda-forge'
        - EVENT_TYPE='pull_request push'

        # If there are matplotlib or other GUI tests, uncomment the following
        # line to use the X virtual framebuffer.
        - SETUP_XVFB=True

    matrix:
        # Make sure that egg_info works without dependencies
        - SETUP_CMD='egg_info'
        - SETUP_CMD='install'
        #- SETUP_CMD='test --coverage'
        - SETUP_CMD='build_docs'

matrix:

    include:
        # Do a PEP8 test with pycodestyle
        - os: linux
          env: MAIN_CMD='pycodestyle synthesizAR --count' SETUP_CMD=''

    allow_failures:
        # Do a PEP8 test with pycodestyle
        # (allow to fail unless your code completely compliant)
        - os: linux
          env: MAIN_CMD='pycodestyle synthesizAR --count' SETUP_CMD=''

install:
    - git clone --depth 1 git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
   - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == *coverage* ]]; then coveralls --rcfile='synthesizAR/tests/coveragerc'; fi