name: synthesizar
channels:
- defaults
- conda-forge
dependencies:
- python=3.6
- astropy
- dask
- distributed
- h5py
- ipywidgets
- matplotlib
- numba
- numpy<1.14
- scipy
- sunpy>=0.8
- yt
- pip:
  - plasmapy
  - git+git://github.com/wtbarnes/fiasco.git
  
