name: synthesizar
channels:
- defaults
- conda-forge
dependencies:
- python=3.6
- numpy=1.13.3
- numba
- scipy
- matplotlib
- h5py
- astropy
- sunpy=0.8.2
- dask
- distributed
- ipywidgets
- yt
- pip:
  - plasmapy
  - git+git://github.com/wtbarnes/fiasco.git
  
