name: synthesizar
channels:
- defaults
- conda-forge
dependencies:
- python=3.6
- numpy
- numba
- scipy
- matplotlib
- h5py
- astropy
- sunpy
- dask
- distributed
- ipywidgets
- yt
- pip:
  - plasmapy
  - git+git://github.com/wtbarnes/fiasco.git
  
