name: synthesizar
channels: !!python/tuple
- defaults
dependencies:
- alabaster=0.7.8=py35_0
- appnope=0.1.0=py35_0
- astropy=1.2.1=np111py35_0
- babel=2.3.3=py35_0
- beautifulsoup4=4.4.1=py35_0
- conda-forge::contextlib2=0.5.3=py35_0
- conda-forge::decorator=4.0.10=py35_0
- conda-forge::glymur=0.8.4=py35_0
- conda-forge::icu=56.1=4
- conda-forge::jpeg=9b=0
- conda-forge::libiconv=1.14=3
- conda-forge::libtiff=4.0.6=6
- conda-forge::libxml2=2.9.4=0
- conda-forge::pandas=0.18.1=np111py35_1
- conda-forge::pillow=3.2.0=py35_1
- conda-forge::pytest=2.9.2=py35_0
- conda-forge::requests=2.11.0=py35_0
- conda-forge::scikit-image=0.12.3=np111py35_0
- conda-forge::suds-jurko=0.6=py35_1
- conda-forge::sunpy=0.7.3=py35_1
- conda-forge::wcsaxes=0.9=py35_0
- cycler=0.10.0=py35_0
- docutils=0.12=py35_2
- entrypoints=0.2.2=py35_0
- freetype=2.5.5=1
- h5py=2.6.0=np111py35_2
- hdf5=1.8.17=1
- imagesize=0.7.1=py35_0
- ipykernel=4.4.1=py35_0
- ipython=5.1.0=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.1=py35_0
- jinja2=2.8=py35_1
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.3.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_core=4.1.1=py35_0
- libpng=1.6.22=0
- libxslt=1.1.28=2
- llvmlite=0.12.1=py35_0
- lxml=3.6.4=py35_0
- markupsafe=0.23=py35_2
- matplotlib=1.5.1=np111py35_0
- mistune=0.7.2=py35_1
- mkl=11.3.3=0
- mpmath=0.19=py35_1
- nbconvert=4.2.0=py35_0
- nbformat=4.1.0=py35_0
- networkx=1.11=py35_0
- notebook=4.2.2=py35_0
- numba=0.27.0=np111py35_0
- numpy=1.11.1=py35_0
- openssl=1.0.2h=2
- path.py=8.2.1=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.3=py35_0
- pip=8.1.2=py35_0
- prompt_toolkit=1.0.3=py35_0
- ptyprocess=0.5.1=py35_0
- py=1.4.31=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=4.11.4=py35_4
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- python.app=1.2=py35_4
- pytz=2016.6.1=py35_0
- pyzmq=15.4.0=py35_0
- qt=4.8.7=4
- qtconsole=4.2.1=py35_0
- readline=6.2=2
- scipy=0.18.0=np111py35_0
- seaborn=0.7.1=py35_0
- setuptools=25.1.6=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sphinx=1.4.1=py35_0
- sphinx_rtd_theme=0.1.9=py35_0
- sqlalchemy=1.0.13=py35_0
- sqlite=3.13.0=0
- sympy=1.0=py35_0
- terminado=0.6=py35_0
- tk=8.5.18=0
- tornado=4.4.1=py35_0
- traitlets=4.2.2=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- yt=3.3.1=py35_0
- zlib=1.2.8=3
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==4.3.0
  - jupyter-console==5.0.0
  - jupyter-core==4.1.1
  - prompt-toolkit==1.0.3
  - git+git://github.com/wtbarnes/solarbextrapolation@setup_fixes#egg=solarbextrapolation
  - sphinx-rtd-theme==0.1.9
