name: synthesizar
channels:
- defaults
- conda-forge
dependencies:
- python=3.5
- ipython=5.1
- ipyparallel
- astropy
- dask
- h5py
- matplotlib
- numba
- numpy
- scipy
- sunpy
- wcsaxes
- yt
- pip:
  - periodictable
  - git+git://github.com/sunpy/solarbextrapolation.git
  - git+git://github.com/chianti-atomic/ChiantiPy.git
