name: synthesizar
channels:
- defaults
- conda-forge
dependencies:
- python=3.6
- astropy
- dask
- distributed
- h5py
- matplotlib
- numba
- numpy
- scipy
- sunpy=0.8
- yt
- pip:
  - plasmapy
  - git+git://github.com/sunpy/solarbextrapolation.git
  - git+git://github.com/wtbarnes/fiasco.git
  
